# Generated by Django 5.1.5 on 2025-02-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
