# Generated by Django 5.1.5 on 2025-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('on_time', "À l'heure"), ('late', 'En retard'), ('absent', 'Absent')], default='on_time', max_length=20),
        ),
    ]
