# Generated by Django 5.1.5 on 2025-02-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_generalworkschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='GeneralWorkSchedule',
        ),
    ]
